---
version: '3.1'

services:
        drupal:         # friendly container name
                image: drupal:8.2
                volumes:
                        - drupal-modules:/var/www/html/modules
                        - drupal-themes:/var/www/html/themes
                        - drupal-sites:/var/www/html/sites
                        - drupal-profiles:/var/www/html/profiles
                ports:
                        - '8090:80'

        postgres:       # friendly container name
                image: postgres:9.6         # build using official postgres
                environment:
                        - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
                volumes:
                        - drupal-data:/var/lib/postgresql/data
                secrets:
                        - postgres_password

volumes:
        drupal-modules:
        drupal-themes:
        drupal-sites:
        drupal-profiles:
        drupal-data:
secrets:
        postgres_password:
                external: true
