---
version: '3.1'

services:
        drupal:         # friendly container name
                build:
                        context: .
                        # build an image using the Dockerfile
                        dockerfile: Dockerfile
                image: custom-drupal
                volumes:
                        - drupal-modules:/var/www/html/modules
                        - drupal-themes:/var/www/html/themes
                        - drupal-sites:/var/www/html/sites
                        - drupal-profiles:/var/www/html/profiles
                ports:
                        - '8080:80'

        postgres:       # friendly container name
                image: postgres         # build using official postgres
                environment:
                        POSTGRES_DB: 'drupal-postgres'
                        POSTGRES_USER: 'postgres'
                        POSTGRES_PASSWORD: '12345678'
                volumes:
                        - drupal-data:/var/lib/postgresql/data

volumes:
        drupal-modules:
        drupal-themes:
        drupal-sites:
        drupal-profiles:
        drupal-data:
